import React, {Component} from 'react';

class Wishlist extends Component {
	render() {
		console.log("ASDDDDDDDDDDDDDDD")
		return (
			<div>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>
			<h1>This is Wish list component Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor et ipsam non sapiente? Autem, cum debitis ea eius illum nam officiis optio possimus, quo rerum, sint sit tenetur vel? A aliquid assumenda cumque ipsum magnam, neque nobis non perferendis quaerat quasi qui quidem reprehenderit, ut vitae voluptates? At autem cupiditate illo possimus provident qui sapiente! Aliquid, autem beatae consequatur consequuntur culpa, dolorem earum eius facilis fugiat iste minus modi nemo non, optio possimus quaerat quibusdam quisquam rem sequi tempore! Aliquam architecto consequatur distinctio dolore eius eligendi itaque iure laboriosam maxime molestias, obcaecati omnis pariatur quasi, quia quos, sunt tempora.</h1>

   </div>
		);
	}
}

export default Wishlist;