export const ACTION_TYPES = {
  FETCH_PRODUCTS: "fetch_products",
  FETCH_PRODUCTS_APPEND: "FETCH_PRODUCTS_APPEND",
  ONE_TYPE_PRODUCTS_FETCH: "ONE_TYPE_PRODUCTS_FETCH",
  COUNT_TOTAL_FILTERABLE_PRODUCT: "COUNT_TOTAL_FILTERABLE_PRODUCT",
  ONE_TYPE_PRODUCTS_LENGTH: "ONE_TYPE_PRODUCTS_LENGTH",
  FETCH_PRODUCT: "fetch_product", 
  CLEAR_PRODUCT_DETAIL: "CLEAR_PRODUCT_DETAIL", 
  FETCH_HOMEPAGE_SECTION_PRODUCTS: "FETCH_HOMEPAGE_SECTION_PRODUCTS",
  LOADER_CIRCLE: "LOADER_CIRCLE",
  CHANGE_PAGINATION: "CHANGE_PAGINATION",
  UNLOCK_FETCHED_DATA: "UNLOCK_FETCHED_DATA",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  INCREASE_CART_ITEM: "INCREASE_CART_ITEM",
  DECREASE_CART_ITEM: "DECREASE_CART_ITEM",
  
  LOGIN: "LOGIN",
  REGISTRATION: "REGISTRATION",
  FETCH_CURRENT_AUTH: "FETCH_CURRENT_AUTH",
  LOGOUT: "LOGOUT",
  
  CHOOSE_LANGUAGE: "CHOOSE_LANGUAGE",
  TOGGLE_NOTIFY: "TOGGLE_NOTIFY",
  ADD_FILTER: "ADD_FILTER",
  SET_filtered_Attributes: "SET_filtered_Attributes",
  SET_currentCategorySelected: "SET_currentCategorySelected",
  
  SET_UI_CATEGORIES: "SET_UI_CATEGORIES",
  SET_UI_CATEGORY_INFO: "SET_UI_CATEGORY_INFO",
  
  SET_BRAND_FOR_CATEGORY: "SET_BRAND_FOR_CATEGORY",
  
  SET_UI_FILTER_ITEM: "SET_UI_FILTER_ITEM",
  
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_BRANDS: "FETCH_BRANDS"

}


export interface CategoryType{
  name: string,
  id: string,
  parentId: string,
  sub?: CategoryType[],
  expand?: boolean
  active?: boolean
}
